### ISSUE TITLE
How can I calculate the  RATE_CONV and RATE_AVERAGE_FILTER_SIZE?

### ISSUE THREAD

**Issue by pi-ko** [MattMgn/foxbot_arduino#1]
Hi,

I don't understand how to calculate the RATE_CONV and RATE_AVERAGE_FILTER_SIZE in your config file.

I use 250RPM motor with 0.034 WHEEL_RADIUS and 0.206 BASE_LENGTH but not move smoothly and so slow to move.

Please suggest me to find   RATE_CONV and RATE_AVERAGE_FILTER_SIZE in your code.

Thank you.

**Comment by MattMgn** [comment]
you could find all the details about this parameter here: https://hackaday.io/project/167074-build-your-own-turtlebot-3-backbone/log/166955-motor-speed-control
